FROM node
VOLUME /TRSS-Yunzai
WORKDIR /TRSS-Yunzai
ENV LANG=C.UTF-8
RUN apt update && apt install -y redis chromium locales \
    fonts-wqy-microhei fonts-wqy-zenhei fonts-arphic-ukai fonts-arphic-uming \
    && npm install pnpm -g && pnpm config set registry https://registry.npmmirror.com \
    && apt clean && rm -rf /tmp/* \
    && git config --global --add safe.directory '*'
EXPOSE 2536/tcp
CMD pnpm i && pnpm start && pnpm run log
