name: Docker Image CI (ACR)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 31 * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Dockerfile
      uses: actions/checkout@v4.1.1
    - name: Alibaba Cloud Container Registry (ACR) Login
      uses: aliyun/acr-login@v1
      with:
          region-id: cn-shenzhen
          login-server: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5.3.0
      with:
          file: Dockerfile-CI
          push: true
          tags: registry.cn-shenzhen.aliyuncs.com/noelle-delta/trss-yunzai
