name: Docker Image CI (ACR)

on:
  schedule:
    - cron: "0 0 * * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Dockerfile
      uses: actions/checkout@v3
    - name: Alibaba Cloud Container Registry (ACR) Login
      uses: aliyun/acr-login@v1
      with:
          login-server: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5.3.0
      with:
          push: true
          tags: noelle-delta/trss-yunzai
